spring:
  application:
    name: file-service-application
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

file:
  upload-dir: D://04. PROJECT//02. Github//FILE-SERVICE//download